name: kafka
services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:latest
    ports:
      - 2181:2181
    volumes:
      - /bitnami
    environment:
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_USERS=kafka
      - ZOO_SERVER_PASSWORDS=kafka_admin_tester
  kafka:
    image: docker.io/bitnami/kafka:latest
    ports:
      - 9092:9092
    volumes:
      - /bitnami
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=SASL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=SASL://:9092
      - KAFKA_ZOOKEEPER_USER=kafka
      - KAFKA_ZOOKEEPER_PASSWORD=kafka_admin_tester
      - KAFKA_CLIENT_USERS=user
      - KAFKA_CLIENT_PASSWORDS=testpassconn
