name: kafka
services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:latest
    ports:
      - 2181
    volumes:
      - /bitnami
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:latest
    ports:
      - '9096:9096'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ZOOKEEPER_PROTOCOL:SASL_PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:SASL_PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9096
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9096
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CLIENT_USERS=kafkausertest
      - KAFKA_CLIENT_PASSWORDS=kafkapasswordtest
    volumes:
      - /bitnami
